source 'https://rubygems.org'

gem 'rails', '3.2.13'
gem 'sqlite3'

gem 'sass-rails',   '~> 3.2.3'
gem 'coffee-rails', '~> 3.2.1'
gem 'uglifier', '>= 1.0.3'
gem 'zurb-foundation'

  gem 'rspec-rails'
  gem 'shoulda-matchers'
  gem 'capybara'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'binding_of_caller'

gem 'jquery-rails'
gem 'bcrypt-ruby', '~> 3.0.0'
gem 'carrierwave'
gem 'mini_magick'
gem 'imgkit'
gem 'websnap'
gem 'smusher'
gem 'sidekiq'
gem 'sinatra', require: false
gem 'slim'
gem 'thin'
gem 'jquery-cookie-rails'
gem 'rmagick'
